### ISSUE TITLE
mamba 

### ISSUE THREAD

**Issue by tariah7** [giswqs/geospatial#25]
i had this error while trying to run  `mamba install geopandas`

`(geo) C:\Users\victor>mamba install geopandas
Traceback (most recent call last):
  File "C:\Users\victor\miniconda3\envs\geo\Scripts\mamba-script.py", line 6, in <module>
    from mamba.mamba import main
  File "C:\Users\victor\miniconda3\envs\geo\lib\site-packages\mamba\mamba.py", line 49, in <module>
    import libmambapy as api
  File "C:\Users\victor\miniconda3\envs\geo\lib\site-packages\libmambapy\__init__.py", line 7, in <module>
    raise e
  File "C:\Users\victor\miniconda3\envs\geo\lib\site-packages\libmambapy\__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
ImportError: DLL load failed while importing bindings: The specified procedure could not be found.`

What could be the problem sir

**Comment by giswqs** [comment]
This appears to be an issue with geopandas rather than geospatial. You can try `mamba install geopandas -c conda-forge`
